spring:
  application:
    name: ms-transaction
  data:
    mongodb:
      uri: mongodb+srv://nttdatadb:nYUK5rr26fpJxkCM@bootcamp48.id8yl1x.mongodb.net/?retryWrites=true&w=majority
      database: test

eureka:
  client:
    #telling the server not to register himself in the service registry
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8093

# Swagger openapi.docs custom path
springdoc:
  api-docs:
    path: transactions/docs
    enabled: true
  swagger-ui:
    path: transactions/docs/ui
    enabled: true
  show-actuator: true

  
#RESILIENCE4J CIRCUIT BREAKER
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      enterpriseactiveloan:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      enterpriseactiveloan:
        base-config: defecto